mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - plugins.split.SplitPlugin
    - plugins.lang.LangPlugin
    - plugins.calendar.CalendarPlugin
context:
    data:
        site_title: Mainframe
        author:
            name: Kreativität trifft Technik
            url: "http://www.kreativitaet-trifft-technik.de"
        home_url: index.html
        menu:
            - title: Home
              basename: home
              type: page
              url: index.html
            - title: {de: Projekte, en: Projects}
              type: menu
              basename: projects
              menu:
                - title: {de: Projektgruppen, en: Projectgroups}
                  url: project_groups.html
                - title: {de: Hardwareprojekte, en: Hardwareprojects}
                  url: project_hardware.html
                - title: {de: Softwareprojekte, en: Softwareprojects}
                  url: project_software.html
                - title: {de: Infrastrukturprojekte, en: Infrastructureprojects}
                  url: project_infrastructure.html
            - title: Events
              type: menu
              basename: events
              menu:
                - title: {de: Kalender, en: Calendar}
                  url: calendar.html
                - title: {de: Vorträge, en: Talks}
                  url: talks.html
                - title: {de: Aktionen, en: Events}
                  url: events.html
            - title: {de: Bilder, en: Images}
              type: menu
              basename: images
              menu:
                - title: Images from Space
                  url: images_from_space.html
                - title: {de: Fotoalben, en: Photo Albums}
                  url: album.html
            - title: {de: Der Verein, en: The Club}
              type: menu
              basename: club
              menu:
                - title: {de: Über Uns, en: About}
                  url: about.html
                - title: {de: Unsere Räume, en: Rooms}
                  url: mainframe.html
                - title: {de: Vereinsgeschichte, en: History}
                  url: history.html
                - title: {de: Mitgliedschaft, en: Membership}
                  url: membership.html
                - title: {de: Satzung und Beitragsordnung, en: Club Rules}
                  url: club_rules.html
                - title: {de: Unterstützen, en: Support}
                  url: support.html
                - title: {de: Pressespiegel, en: Press Review}
                  url: press_review.html
                - title: {de: Pressemitteilungen, en: Press Releases}
                  url: press_release.html
            - title: {en: Contact, de: Kontakt}
              type: page
              basename: contact
              url: contact.de.html

sorter:
    time:
        attr:
            - meta.created
        reverse: true
        filters:
            source.kind: html
            meta.listable: true
